CREATE TABLE notes (
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    workspace_id    BIGINT UNSIGNED NOT NULL,
    folder_id       BIGINT UNSIGNED DEFAULT NULL,
    title           VARCHAR(512)    NOT NULL,
    slug            VARCHAR(512)    NOT NULL,
    content_md      MEDIUMTEXT      NOT NULL DEFAULT '',
    content_html    MEDIUMTEXT      NOT NULL DEFAULT '',
    content_json    JSON            DEFAULT NULL,
    author_id       BIGINT UNSIGNED NOT NULL,
    is_pinned       BOOLEAN         NOT NULL DEFAULT FALSE,
    is_archived     BOOLEAN         NOT NULL DEFAULT FALSE,
    word_count      INT UNSIGNED    NOT NULL DEFAULT 0,
    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_n_ws (workspace_id),
    INDEX idx_n_folder (folder_id),
    INDEX idx_n_author (author_id),
    INDEX idx_n_slug (workspace_id, slug),
    INDEX idx_n_updated (updated_at),
    FULLTEXT INDEX ft_n_search (title, content_md),
    CONSTRAINT fk_n_ws     FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_n_folder FOREIGN KEY (folder_id)    REFERENCES folders(id)    ON DELETE SET NULL,
    CONSTRAINT fk_n_author FOREIGN KEY (author_id)    REFERENCES users(id)      ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
